# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoat < Formula
  desc "Terminal-native SQLite and PostgreSQL TUI client"
  homepage "https://github.com/jxdones/stoat"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jxdones/stoat/releases/download/v0.9.0/stoat_0.9.0_darwin_amd64.tar.gz"
      sha256 "a3687026bb68304132f06ddcecfab19da39a13bde5461cd100baa5dcbc5a1299"

      define_method(:install) do
        bin.install "stoat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jxdones/stoat/releases/download/v0.9.0/stoat_0.9.0_darwin_arm64.tar.gz"
      sha256 "13410a910a8da6cc6097353d726e89fab1a2b83083ba1156c10715cc01a167ba"

      define_method(:install) do
        bin.install "stoat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jxdones/stoat/releases/download/v0.9.0/stoat_0.9.0_linux_amd64.tar.gz"
      sha256 "9c9bf75fee9a9d0459587d160887ed2630ffa394f3fa57acb3173899ba2b0a2d"
      define_method(:install) do
        bin.install "stoat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jxdones/stoat/releases/download/v0.9.0/stoat_0.9.0_linux_arm64.tar.gz"
      sha256 "0d89840a8659876c127e0b658d565b81c6a55893afbb031af8b7d62f42a254b5"
      define_method(:install) do
        bin.install "stoat"
      end
    end
  end

  test do
    system "#{bin}/stoat", "--version"
  end
end
