# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoat < Formula
  desc "Terminal-native SQLite and PostgreSQL TUI client"
  homepage "https://github.com/jxdones/stoat"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jxdones/stoat/releases/download/v0.8.0/stoat_0.8.0_darwin_amd64.tar.gz"
      sha256 "83a1ad07dac94c20fe8bd91351039e5c0366a532dcb42058eae62af2434e32f6"

      define_method(:install) do
        bin.install "stoat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jxdones/stoat/releases/download/v0.8.0/stoat_0.8.0_darwin_arm64.tar.gz"
      sha256 "39c5de3ada0589f3586b250b89b35723e9bcbf0c71a44bd0db058d36eb027895"

      define_method(:install) do
        bin.install "stoat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jxdones/stoat/releases/download/v0.8.0/stoat_0.8.0_linux_amd64.tar.gz"
      sha256 "71fd8d7367139c64e8f64a1dceeadcdfd128b2f7d7a417da31e9c44fba72a961"
      define_method(:install) do
        bin.install "stoat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jxdones/stoat/releases/download/v0.8.0/stoat_0.8.0_linux_arm64.tar.gz"
      sha256 "e1f6c54d9f55995030534603c8426759daa5d86eb6fd23c89bd157c7bbc654be"
      define_method(:install) do
        bin.install "stoat"
      end
    end
  end

  test do
    system "#{bin}/stoat", "--version"
  end
end
