# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoat" do
  version "0.14.3"

  on_macos do
    on_intel do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_darwin_amd64.tar.gz"
      sha256 "b2bbf59f85c2d0884d4f8ead22f65e334b5c6953fe42b73603581887e757cf88"
    end
    on_arm do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_darwin_arm64.tar.gz"
      sha256 "d05518161e3ec1795e846121894fbf80c15958dd9249f661e6def8207f0933ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_linux_amd64.tar.gz"
      sha256 "9a64f70823edb8ec9a0562f1ec4fa96bd055d6e1821e3b7c32c912a74db7f9ee"
    end
    on_arm do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_linux_arm64.tar.gz"
      sha256 "85a6cbfd9e43f9954a0fa87b9b946de9b5529392ef859e2ae1800becce6332c2"
    end
  end

  name "stoat"
  desc "The database client for people who don't leave the terminal."
  homepage "https://github.com/jxdones/stoat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoat"

  # No zap stanza required

end
