# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoat" do
  version "0.14.5"

  on_macos do
    on_intel do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_darwin_amd64.tar.gz"
      sha256 "a2155aad8ba73d3f6be45b9da986210cb18f681eff3c1b41f8b1af7287015ff5"
    end
    on_arm do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_darwin_arm64.tar.gz"
      sha256 "a37a43c33dbb717920106a4650a5e3fab4d7d4c2bbc5e4711210fcfabb85e5aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_linux_amd64.tar.gz"
      sha256 "b2e4f462c88e38637a300de6d693bfb46239496732fc9dfd59070fab7d175ace"
    end
    on_arm do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_linux_arm64.tar.gz"
      sha256 "a37e19b6eb496385e99481c96f82e00e34f0f715059015cbc297c51d5d87cfe3"
    end
  end

  name "stoat"
  desc "The database client for people who don't leave the terminal."
  homepage "https://github.com/jxdones/stoat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoat"

  # No zap stanza required

end
