# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoat" do
  name "stoat"
  desc "The database client for people who don't leave the terminal."
  homepage "https://github.com/jxdones/stoat"
  version "0.14.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoat"

  on_macos do
    on_intel do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_darwin_amd64.tar.gz"
      sha256 "9c11fe622e7fd13830e592adb6d4631aec5a488e235b1d6059b4773c78f1bc5e"
    end
    on_arm do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_darwin_arm64.tar.gz"
      sha256 "b0579bff37b4f1e236c13d00a2337f68d722df7302711edc49a78ad100ab1846"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_linux_amd64.tar.gz"
      sha256 "f0987df202598fe680b39e81de6b1d3d1dd0d52905ab9c1abcc2fa02e67f8b52"
    end
    on_arm do
      url "https://github.com/jxdones/stoat/releases/download/v#{version}/stoat_#{version}_linux_arm64.tar.gz"
      sha256 "98bc79b31de986e4eeb389947daec0a0a1f24974a03fb802fe3a62ebe43d7901"
    end
  end

  # No zap stanza required
end
